# Generated by Django 4.2.7 on 2025-05-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeanalysis',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='analysis_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ats_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='career_progression_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='current_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='experience_gaps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='formatting_feedback',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='next_steps',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='skill_level_assessment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='strengths',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='suggested_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='target_role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='weaknesses',
            field=models.JSONField(default=list),
        ),
    ]
